#!/usr/bin/env python

import sys 


def main( inistr ):
    
    
    
    try:
        from mpi4py import MPI
    except ImportError:
        raise RuntimeError("mpi4py MPI environment not found!")
    
    comm = MPI.COMM_WORLD 
    
    print "Hello world"  



if __name__=="__main__":
    if ( len(sys.argv) )==2:
        main( str(sys.argv[1] ))
    else:
        print 'Usage: mpirun pypower [inifile.ini]'


