#!/usr/bin/env python

import sys 

from lib.config import IniFile
from lib.model import Model
from lib.integrator import Integrator
from lib.sampler import Sampler
from lib.output import Output

def main( inistr ):
    
    
    
    try:
        from mpi4py import MPI
    except ImportError:
        raise RuntimeError("mpi4py MPI environment not found!")
    
    comm = MPI.COMM_WORLD 
    
    ini = IniFile( inistr )
    
    myModel = Model( ini, comm )
    myModel.config()
    
    myOutput = Output( ini, comm )
    myOutput.config()
    
    myIntegrator = Integrator( ini, comm, myModel, myOutput )
    myIntegrator.config()
    
    mySampler = Sampler( ini, comm, myModel, myIntegrator, myOutput )
    mySampler.config()
    
    mySampler.run()
    
    myOutput.save()
     
    
    print "Done!"



if __name__=="__main__":
    if ( len(sys.argv) )==2:
        main( str(sys.argv[1] ))
    else:
        print 'Usage: mpirun pypower [inifile.ini]'


